#!/bin/python
from sys import argv
n, c = argv[1:3]
rgb = [int(c[i+1:i+3], 16)/255 for i in range(0,6,2)]
r, g, b = rgb
m = max(rgb) - min(rgb)
if not m:
  h = 0.0
else:
  i = sorted(enumerate(rgb), key = lambda x: x[1])[0][0]
  h = (2*i) + ([g-b, b-r, r-g][i]/m)
l = 0.299*r + 0.587*g + 0.114*b
print(h, l, c, n)
