#!/usr/bin/perl
chdir '/home/c/img/bg/';
$W = (`i3_get_output` eq 'HDMI-0' ? 1280 : 1440) - 2;
chomp(@files = `ls -tb`);
if (@bg = `feh -Twalls -W $W @files`) {
  system "wal -i $bg[-1]";
  system 'pywalfox update';
}
