#!/usr/bin/perl
chdir '/your/wall/dir/'

use strict;
use List::Util qw(min max reduce);

sub info {
  my ($c, $n) = @_;
  my @rgb = ((substr $c, 1) =~ m/../g);
  @rgb = map { hex() / 255 } @rgb;
  my $m = max(@rgb) - min(@rgb);
  my $h = $m == 0 ? 0 : &hue($m, @rgb);
  my $l = reduce { $a + $rgb[$b] * (0.299, 0.587, 0.114)[$b] } 0, 0..3;     
  return "$h $l $c $n\n";
}

sub hue {
  my ($m, @rgb) = @_;
  my $i = reduce { $rgb[$a] > $rgb[$b] ? $a : $b } 0..3;
  my @s = map { $rgb[($_+1)%3] - $rgb[($_+2)%3] } 0..3;
  return 2 * $i + $s[$i] / $m;
}

my $n = scalar @ARGV;
my $i = 1;
foreach(@ARGV){
  my $C = (split / /, (`convert $_ -scale 1x1 txt:-`)[-1])[3];
  open (my $HUES, '>>', 'hues') or die 'can\'t open hues';
  print $HUES &info($C, $_);
  print "$i/$n $_\n";
  $i++;
}

